# Logistic Regression Using Scikit-Learn

In [2]:
# Load libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.preprocessing import label_binarize
import warnings

# Suppress Warning
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

C:\Users\computer\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Load Iris Flower Dataset

In [3]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Standardize Features

In [4]:
# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Train Logistic Regression using 'liblinear' solver

In [14]:
# Create logistic regression object using sag solver
clf = LogisticRegression(solver='liblinear',random_state=0)

# Train model
model3 = clf.fit(X_std, y)

# View Intercept

In [17]:
model3.intercept_

array([-1.61861686, -0.89769778, -2.70851029])

# View Coefficients

In [18]:
model3.coef_

array([[-0.81016631,  1.39369878, -1.68738578, -1.51899135],
       [ 0.13037985, -1.2463382 ,  0.78919477, -0.88943988],
       [ 0.01299039, -0.1445346 ,  1.86317337,  2.69887272]])

# Accuracy

In [19]:
model3.score(X_std, y)

0.92666666666666664

# Train Logistic Regression using 'SAG' solver

In [20]:
# Create logistic regression object using sag solver
clf = LogisticRegression(solver='sag',random_state=0)

# Train model
model2 = clf.fit(X_std, y)

# View Intercept

In [21]:
model2.intercept_

array([-2.48478977, -0.93821439, -3.79951294])

# View Coefficients

In [22]:
model2.coef_

array([[-1.05903725,  1.22294709, -1.76426377, -1.63734782],
       [ 0.13003099, -1.26242676,  0.79587666, -0.8919623 ],
       [ 0.13996749, -0.51271371,  2.48225359,  3.14081927]])

# Accuracy

In [23]:
model2.score(X_std, y)

0.94666666666666666

Thus, we were able to compare logistic regression and logistic regression with stochastic average gradient descent using sklearn.